routes/web.php
<?php

use App\Http\Controllers\Admin\DaerahPondokController;
use App\Http\Controllers\Admin\DashboardController;
use App\Http\Controllers\Admin\MemberController;
use App\Http\Controllers\Admin\ProgramController;
use App\Http\Controllers\Admin\UserController;
use App\Http\Controllers\Admin\VisitController;
use Illuminate\Support\Facades\Route;
use App\Http\Controllers\StaterkitController;
use App\Http\Controllers\LanguageController;

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

// Route::get('/', [StaterkitController::class, 'home'])->name('home');
// Route::get('home', [StaterkitController::class, 'home'])->name('home');
// Route Components
Route::get('layouts/collapsed-menu', [StaterkitController::class, 'collapsed_menu'])->name('collapsed-menu');
Route::get('layouts/full', [StaterkitController::class, 'layout_full'])->name('layout-full');
Route::get('layouts/without-menu', [StaterkitController::class, 'without_menu'])->name('without-menu');
Route::get('layouts/empty', [StaterkitController::class, 'layout_empty'])->name('layout-empty');
Route::get('layouts/blank', [StaterkitController::class, 'layout_blank'])->name('layout-blank');
Route::get('/', [DashboardController::class, 'index']);
Route::prefix('admin')->group(function () {

    Route::post('member/{id}/delete', [MemberController::class, 'delete'])->name('member.delete');
    Route::resource('member', MemberController::class);
    Route::resource('user', UserController::class);
    Route::resource('daerah-pondok', DaerahPondokController::class);
    Route::resource('visit', VisitController::class);
    Route::resource('program', ProgramController::class);

    Route::group(['prefix' => 'datatables'], function () {
        Route::get('/permission/all', [PermissionsController::class, 'data'])->name('permission.data');
        Route::get('/role/all', [RolesController::class, 'data'])->name('role.data');
        Route::get('/users/all', [UserController::class, 'data'])->name('user.data');
        Route::get('/member/all', [MemberController::class, 'data'])->name('member.data');
        Route::get('/visit/all', [VisitController::class, 'data'])->name('visit.data');

    });
});


// locale Route
Route::get('lang/{locale}', [LanguageController::class, 'swap']);

app/Models/Visit.php
<?php

namespace App\Models;

use Illuminate\Database\Eloquent\Model;

class Visit extends Model
{
    protected $fillable = [
        'id_visitor1',
        'id_visitor2',
        'id_visitor3',
        'id_materi1',
        'id_materi2',
        'id_materi3',
        'id_materi4',
        'id_materi5',
        'id_daerah_pondok',
        'dari',
        'sampai',
        'kendala',
        'kebutuhan',
        'saran',
        'flag'
    ];

    public function visitor1() {
        return $this->belongsTo(Member::class, 'id_visitor1');
    }

    public function visitor2() {
        return $this->belongsTo(Member::class, 'id_visitor2');
    }

    public function visitor3() {
        return $this->belongsTo(Member::class, 'id_visitor3');
    }

    public function daerah() {
        return $this->belongsTo(DaerahPondok::class, 'id_daerah_pondok');
    }

}

app/Http/Controllers/Admin/VisitController.php
<?php

namespace App\Http\Controllers\Admin;

use App\Http\Controllers\Controller;
use App\Models\DaerahPondok;
use App\Models\Matter;
use App\Models\Member;
use App\Models\Role;
use App\Models\Visit;
use App\Services\Admin\VisitService;
use Illuminate\Http\Request;

class VisitController extends Controller
{
    protected $service;

    public function __construct(
        VisitService $service
    )
    {
        $this->service = $service;
    }

    public function index()
    {
        # code...
        return view('pages.admin.visit.index');
    }

    public function data(Request $request)
    {
        # code...
        return $this->service->data($request);
    }

    public function create()
    {
        $visitor = Member::where('id_role', '4')->get();
        $daerahPondok = DaerahPondok::where('flag', '1')->get();
        $roles = Role::all();
        $matters = Matter::where('flag', 1)->get();

        return view('pages.admin.visit.create', compact('visitor', 'daerahPondok', 'roles', 'matters'));
    }

    public function edit($id)
    {
        $item = Visit::find($id);
        $visitor = Member::where('id_role', '4')->get();
        $daerahPondok = DaerahPondok::where('flag', '1')->get();
        $matters = Matter::where('flag', 1)->get();
        $roles = Role::all();

        return view('pages.admin.visit.edit', compact('visitor', 'matters', 'daerahPondok', 'roles', 'item'));
    }

    public function store(Request $request)
    {
        # code...
        return $this->service->store($request);
    }

    public function update(Request $request, $id)
    {
        # code...
        return $this->service->update($request, $id);
    }

    public function destroy($id)
    {
        # code...
        return $this->service->destroy($id);
    }
}

resources/views/pages/admin/visit/create.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Form Create')

@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection

@section('content')
    <!-- Basic Horizontal form layout section start -->

    @if (session('success'))
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Success</h4>
            <div class="alert-body">
                {{ session('success') }}
            </div>
        </div>
    @endif
    @if (session('failed'))
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Warning</h4>
            <div class="alert-body">
                {{ session('failed') }}
            </div>
        </div>
    @endif
    <section id="basic-horizontal-layouts">
        <div class="row">
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Create Form</h4>
                    </div>
                    <div class="card-body">
                        <form class="form form-vertical" action="{{ route('visit.store') }}" method="POST">
                            @csrf
                            <div class="row">
                                <div class="col-12">
                                    <div class="mb-1 row">
                                        <div class="col-sm-3">
                                            <label for="">Tujuan Visit</label>
                                        </div>
                                        <div class="col-sm-9">
                                            <select name="id_daerah_pondok" id="id_daerah_pondok" class="form-control">
                                                <option value="">Pilih Daerah / Pondok</option>
                                                @foreach ($daerahPondok as $value)
                                                    <option value="{{ $value->id }}"
                                                        {{ old('id_daerah_pondok') == $value->id ? 'selected' : '' }}>
                                                        {{ $value->type->nama }} {{ $value->nama }}
                                                    </option>
                                                @endforeach
                                            </select>
                                        </div>
                                    </div>
                                    <div class="mb-1 row">
                                        <div class="col-sm-3">
                                            <label class="col-form-label" for="select2-multiple">Visitor</label>
                                        </div>
                                        <div class="col-sm-9">
                                            <select class="select2 form-select" multiple="true multiple" name="id_visitor1[]"
                                                id="select2-multiple" multiple>
                                                <optgroup label="Visitor">
                                                    @foreach ($visitor as $value)
                                                        <option value="{{ $value->id }}">{{ $value->nama }}</option>
                                                    @endforeach
                                                </optgroup>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="mb-1 row">
                                        <div class="col-sm-3">
                                            <label class="col-form-label" for="select2-multiple">Materi</label>
                                        </div>
                                        <div class="col-sm-9">
                                            <select class="select2 form-select" multiple="true multiple" name="id_materi1[]"
                                                id="select2-multiple2" multiple>
                                                <optgroup label="Materi">
                                                    @foreach ($matters as $value)
                                                        <option value="{{ $value->id }}">{{ $value->nama }}</option>
                                                    @endforeach
                                                </optgroup>
                                            </select>
                                        </div>
                                    </div>
                                    <div class="mb-3">
                                        <div class="row">
                                            <div class="col-6">
                                                <label class="form-label" for="dari">Dari</label>
                                                <input type="date"
                                                    class="form-control input-default @error('dari') is-invalid @enderror"
                                                    name="dari" autocomplete="off" required value="{{ old('dari') }}"
                                                    id="dari">
                                                @error('dari')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                            <div class="col-6">
                                                <label class="form-label" for="sampai">Sampai</label>
                                                <input type="date"
                                                    class="form-control input-default @error('sampai') is-invalid @enderror"
                                                    name="sampai" autocomplete="off" required value="{{ old('sampai') }}"
                                                    id="sampai">
                                                @error('sampai')
                                                    <div class="invalid-feedback">{{ $message }}</div>
                                                @enderror
                                            </div>
                                        </div>
                                    </div>
                                    {{-- <div class="mb-3">
                                        <label class="form-label" for="materi">Materi</label>
                                        <textarea name="materi" class="form-control ckeditor" id="materi" cols="30"
                                            rows="10">{{ old('materi') }}</textarea>
                                    </div> --}}
                                    <div class="mb-3">
                                        <label class="form-label" for="kendala">Kendala</label>
                                        <textarea name="kendala" class="form-control ckeditor" id="kendala" cols="30"
                                            rows="10">{{ old('kendala') }}</textarea>
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label" for="kebutuhan">Kebutuhan</label>
                                        <textarea name="kebutuhan" class="form-control ckeditor" id="kebutuhan" cols="30"
                                            rows="10">{{ old('kebutuhan') }}</textarea>
                                    </div>
                                    <div class="mb-3">
                                        <label class="form-label" for="saran">Saran</label>
                                        <textarea name="saran" class="form-control ckeditor" id="saran" cols="30"
                                            rows="10">{{ old('saran') }}</textarea>
                                    </div>
                                </div>
                                <div class="col-12">
                                    <button type="submit"
                                        class="btn btn-primary me-1 waves-effect waves-float waves-light">Submit</button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Basic Horizontal form layout section end -->

@endsection
@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection
@section('page-script')
    <script src="//cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
    <script>
        $(document).ready(function() {
            $('.ckeditor').ckeditor();
        });
    </script>
    <script src="{{ asset(mix('js/scripts/forms/form-select2.js')) }}"></script>
@endsection

resources/views/pages/admin/visit/edit.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Form Edit')

@section('vendor-style')
    <!-- vendor css files -->
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/forms/select/select2.min.css')) }}">
@endsection
@section('content')
    <!-- Basic Horizontal form layout section start -->

    @if (session('success'))
        <div class="alert alert-success" role="alert">
            <h4 class="alert-heading">Success</h4>
            <div class="alert-body">
                {{ session('success') }}
            </div>
        </div>
    @endif
    @if (session('failed'))
        <div class="alert alert-danger" role="alert">
            <h4 class="alert-heading">Warning</h4>
            <div class="alert-body">
                {{ session('failed') }}
            </div>
        </div>
    @endif
    <section id="basic-horizontal-layouts">
        <div class="row">
            <div class="col-md-12 col-12">
                <div class="card">
                    <div class="card-header">
                        <h4 class="card-title">Edit Form</h4>
                    </div>
                    <div class="card-body">
                        <form class="form form-vertical" action="{{ route('visit.update', $item->id) }}" method="POST">
                            @csrf
                            @method('put')
                          <div class="row">
                            <div class="col-12">
                                <div class="mb-1 row">
                                    <div class="col-sm-3">
                                        <label for="">Tujuan Visit</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <select name="id_daerah_pondok" id="id_daerah_pondok" class="form-control">
                                            <option value="">Pilih Daerah / Pondok</option>
                                            @foreach ($daerahPondok as $value)
                                                <option value="{{ $value->id }}"
                                                    {{$item->id_daerah_pondok==$value->id ? 'selected' : ''}}>
                                                    @if ($value->jenis == 1)
                                                Pondok Pesantren
                                                @elseif ($value->jenis == 2)
                                                Pondok Pesantren Mahasiswa
                                                @elseif ($value->jenis == 3)
                                                Pondok Pesantren Pelajar & Mahasiswa
                                                @elseif ($value->jenis == 4)
                                                Daerah
                                                @endif
                                                {{ $value->nama }}</option>
                                            @endforeach
                                        </select>
                                    </div>
                                </div>
                                <div class="mb-1 row">
                                    <div class="col-sm-3">
                                        <label class="col-form-label" for="select2-multiple">Visitor</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <select class="select2 form-select" multiple="true multiple" name="id_visitor1[]"
                                            id="select2-multiple" multiple>
                                            <optgroup label="Visitor">
                                                @foreach ($visitor as $value)
                                                    <option value="{{ $value->id }}"
                                                        @if ($value->id == $item->id_visitor1)
                                                        selected
                                                        @elseif ($value->id == $item->id_visitor2)
                                                        selected
                                                        @elseif ($value->id == $item->id_visitor3)
                                                        selected
                                                    @endif>{{ $value->nama }}</option>
                                                @endforeach
                                            </optgroup>
                                        </select>
                                    </div>
                                </div>
                                <div class="mb-1 row">
                                    <div class="col-sm-3">
                                        <label class="col-form-label" for="select2-multiple">Materi</label>
                                    </div>
                                    <div class="col-sm-9">
                                        <select class="select2 form-select" multiple="true multiple" name="id_materi1[]"
                                            id="select2-multiple2" multiple>
                                            <optgroup label="Materi">
                                                @foreach ($matters as $value)
                                                    <option value="{{ $value->id }}"
                                                        @if ($value->id == $item->id_materi1)
                                                        selected
                                                        @elseif ($value->id == $item->id_materi2)
                                                        selected
                                                        @elseif ($value->id == $item->id_materi3)
                                                        selected
                                                        @elseif ($value->id == $item->id_materi4)
                                                        selected
                                                        @elseif ($value->id == $item->id_materi5)
                                                        selected
                                                        @endif
                                                        >{{ $value->nama }}</option>
                                                @endforeach
                                            </optgroup>
                                        </select>
                                    </div>
                                </div>
                              <div class="mb-3">
                                  <div class="row">
                                      <div class="col-6">
                                          <label class="form-label" for="dari">Dari</label>
                                          <input type="date"
                                              class="form-control input-default @error('dari') is-invalid @enderror"
                                              name="dari" autocomplete="off" required value="{{ $item->dari }}"
                                              id="dari">
                                          @error('dari')
                                              <div class="invalid-feedback">{{ $message }}</div>
                                          @enderror
                                      </div>
                                      <div class="col-6">
                                          <label class="form-label" for="sampai">Sampai</label>
                                          <input type="date"
                                              class="form-control input-default @error('sampai') is-invalid @enderror"
                                              name="sampai" autocomplete="off" required value="{{ $item->sampai }}"
                                              id="sampai">
                                          @error('sampai')
                                              <div class="invalid-feedback">{{ $message }}</div>
                                          @enderror
                                      </div>
                                  </div>
                              </div>
                              <div class="mb-3">
                                <label class="form-label" for="kendala">Kendala</label>
                                <textarea name="kendala" class="form-control ckeditor" id="kendala" cols="30" rows="10">{{ $item->kendala }}</textarea>
                              </div>
                              <div class="mb-3">
                                <label class="form-label" for="kebutuhan">Kebutuhan</label>
                                <textarea name="kebutuhan" class="form-control ckeditor" id="kebutuhan" cols="30" rows="10">{{ $item->kebutuhan }}</textarea>
                              </div>
                              <div class="mb-3">
                                <label class="form-label" for="saran">Saran</label>
                                <textarea name="saran" class="form-control ckeditor" id="saran" cols="30" rows="10">{{ $item->saran }}</textarea>
                              </div>
                            </div>
                            <div class="col-12">
                              <button type="submit" class="btn btn-primary me-1 waves-effect waves-float waves-light">Update</button>
                            </div>
                          </div>
                        </form>
                      </div>
                </div>
            </div>
        </div>
    </section>
    <!-- Basic Horizontal form layout section end -->

@endsection
@section('vendor-script')
    <!-- vendor files -->
    <script src="{{ asset(mix('vendors/js/forms/select/select2.full.min.js')) }}"></script>
@endsection
@section('page-script')
    <script src="//cdn.ckeditor.com/4.17.2/standard/ckeditor.js"></script>
    <script>
        $(document).ready(function() {
            $('.ckeditor').ckeditor();
        });
    </script>
    <script src="{{ asset(mix('js/scripts/forms/form-select2.js')) }}"></script>
@endsection

resources/views/pages/admin/visit/index.blade.php
@extends('layouts/contentLayoutMaster')

@section('title', 'Data Visit')

@section('vendor-style')
    {{-- vendor css files --}}
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/dataTables.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/responsive.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/buttons.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/tables/datatable/rowGroup.bootstrap5.min.css')) }}">
    <link rel="stylesheet" href="{{ asset(mix('vendors/css/pickers/flatpickr/flatpickr.min.css')) }}">
@endsection

@section('content')
    @if (session('success'))
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Success</h4>
            <div class="alert-body">
                {{ session('success') }}
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    @if (session('failed'))
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            <h4 class="alert-heading">Warning</h4>
            <div class="alert-body">
                {{ session('failed') }}
            </div>
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
    @endif
    @if ($errors->any())
        <div class="alert alert-danger alert-dismissible fade show mb-0" role="alert">
            <ul>
                @foreach ($errors->all() as $error)
                    <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close">
                    </button>
                    <li>{{ $error }}</li>
                @endforeach
            </ul>
        </div>
    @endif

    <!-- Basic table -->
    <section id="basic-datatable">
        <div class="row">
            <div class="col-12">
                <div class="card">
                    <table class="datatables-basic table">
                        <thead>
                            <tr>
                                <th>Dari</th>
                                <th>Sampai</th>
                                <th>Tujuan</th>
                                <th>Visitor 1</th>
                                <th>Visitor 2</th>
                                <th>Visitor 3</th>
                                <th>Aksi</th>
                            </tr>
                        </thead>
                    </table>
                </div>
            </div>
        </div>
        <!-- Modal Delete -->
        <div id="deleteModal" class="modal fade" role="dialog">
            <div class="modal-dialog">
                <div class="modal-content">
                    <div class="modal-header">
                        <h2 class="modal-title">Confirmation</h2>
                    </div>
                    <div class="modal-body">
                        <h4 align="center" style="margin:0;">Are you sure you want to remove this data?</h4>
                    </div>
                    <div class="modal-footer">
                        <button type="button" name="ok_button" id="ok_button" class="btn btn-danger">OK</button>
                        <button type="reset" class="btn btn-default" data-bs-dismiss="modal">Cancel</button>
                    </div>
                </div>
            </div>
        </div>
    </section>
    <!--/ Basic table -->
@endsection


@section('vendor-script')
    {{-- vendor files --}}
    <script src="{{ asset(mix('vendors/js/tables/datatable/jquery.dataTables.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.bootstrap5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.responsive.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/responsive.bootstrap5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.checkboxes.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/datatables.buttons.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/jszip.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/pdfmake.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/vfs_fonts.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.html5.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/buttons.print.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/tables/datatable/dataTables.rowGroup.min.js')) }}"></script>
    <script src="{{ asset(mix('vendors/js/pickers/flatpickr/flatpickr.min.js')) }}"></script>
@endsection

@section('page-script')
    {{-- Page js files --}}
    <script src="{{ asset('js/scripts/tables/table-visit.js') }}"></script>
@endsection